[package]
name = "webvwr"
version = "0.1.1"
edition = "2021"

[dependencies]
wry = "0.26.0"
clap = "4.3.0"
scraper = "0.12.0"
site_icons = "0.6.4"
reqwest = {version = "0.11", features = ["blocking"]}
#directories = "5.0"